import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import avatar from '../public/avatar1.png'
import logo from '../public/logo.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Sharlon Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`max-w-screen-lg min-h-screen mx-auto ${inter.className}`}>
        <header className='flex items-center justify-between p-4'>
          <Image
            className='inline-block w-20 h-20'
            src={logo}
            alt="Picture of Sharlon Balbalosa"
          />
          <nav>
            <ul className='flex gap-8 text-lg font-semibold'>
              <ol>About</ol>
              <ol>Resume</ol>
              <ol>Blog</ol>
            </ul>
          </nav>
        </header>
        <main className='p-4'>
          <div className='flex mt-8'>
            <div className='flex-1 mt-6'>
              <h1 className="text-5xl font-semibold">
                Hi my name is <br />
                <span className='text-white'>Sharlon Balbalosa</span>
                <br />I am a <span className="text-white">Frontend/Full Stack</span> Developer
              </h1>
              {/* <p className='text-xl'>I am a Frontend/Full Stack Developer <br />with proven track record of building scalable applications thru</p> */}
              <button className='px-4 py-2 mt-8 font-bold text-white bg-gray-700 rounded ring-white ring-1 hover:bg-black'>Lets Talk</button>
            </div>
            <div className='relative h-60 w-60'>
              <Image
                className='inline-block rounded-full h-52 w-52 ring-2 ring-white'
                src={avatar}
                alt="Picture of Sharlon Balbalosa"
              />
              <div
                className="absolute px-4 py-2 text-xl font-semibold text-white bg-gray-700 rounded-lg -left-8 bottom-8"
              >
                <p>12 YRS+</p>
                <p className='text-sm font-normal'>Experience</p>
              </div>
            </div>
          </div>
          {/* <ul className='flex gap-2 mt-8'>
            <ol className="p-2 font-bold">JavaScript</ol>
            <ol className="p-2 font-bold">TypeScript</ol>
            <ol className="p-2 font-bold">HTML</ol>
            <ol className="p-2 font-bold">CSS</ol>
            <ol className="p-2 font-bold">NodeJS</ol>
            <ol className="p-2 font-bold">SQL</ol>
          </ul>
          <h2 className="text-4xl font-semibold">Work Experience</h2>
          <ul className='flex gap-2'>
            <ol className="p-2 font-bold">CoachHub</ol>
            <ol className="p-2 font-bold">Deloitte</ol>
            <ol className="p-2 font-bold">Deltek</ol>
          </ul> */}
        </main>
        {/* <footer className="p-4">Footer</footer> */}
      </div>
    </>
  )
}
