import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import avatar from '../public/avatar1.png'
import javascript from "../public/javascript.png"
import react from "../public/react.png"
import typescript from "../public/typescript.png"
import html5 from "../public/html5.png"
import node from "../public/node.png"
import link from "../public/link.png"
import SkillBar from '@/components/SkillBar'
import MoreSkills from '@/components/MoreSkills'
import IntroText from '@/components/IntroText'
import Logo from '@/components/Logo'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Sharlon Balbalosa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`max-w-screen-lg min-h-screen mx-auto ${inter.className}`}>
        <header className='flex items-center justify-between p-4 '>
          <Logo />
          <a className="hidden text-gray-600 uppercase cursor-pointer md:block hover:text-white" href="mailto:sbalbalosa@gmail.com" title="sbalbalos@gmail.com">sbalbalosa@gmail.com</a>
        </header>
        <main className='p-4'>
          <div className='flex items-center mt-8'>
            <IntroText />
            <div className='relative h-60 w-60'>
              <Image
                className='inline-block rounded-full h-52 w-52 ring-2 ring-white'
                src={avatar}
                alt="Picture of Sharlon Balbalosa"
              />
              <div
                className="absolute px-4 py-2 text-xl font-semibold text-white bg-gray-700 rounded-lg -left-8 bottom-8"
              >
                <p>12 YRS+</p>
                <p className='text-sm font-normal'>Experience</p>
              </div>
            </div>
          </div>
          <div className='mt-32'>
            <h1 className="text-3xl font-semibold text-white">
              Technologies
            </h1>
            <div className="w-full px-2 pt-8 ">
              <div className="flex flex-row">
                <div className="pr-4">
                  <Image
                    className='inline-block w-16 h-16'
                    src={javascript}
                    alt="logo of javascript"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="text-lg font-semibold text-white">JavaScript</span>
                    <span className="px-2 py-1 bg-gray-600 rounded-lg text-md text-white font-medium min-w-[46px] text-center">12+ YRS</span>
                  </div>
                  <SkillBar from={0} to={100} />
                </div>
              </div>
              <div className="flex flex-row">
                <div className="pr-4">
                  <Image
                    className='inline-block w-16 h-16'
                    src={html5}
                    alt="logo of html5"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="text-lg font-semibold text-white">HTML/CSS</span>
                    <span className="px-2 py-1 bg-gray-600 rounded-lg text-md text-white font-medium min-w-[46px] text-center">12+ YRS</span>
                  </div>
                  <SkillBar from={0} to={100} />
                </div>
              </div>
              <div className="flex flex-row">
                <div className="pr-4">
                  <Image
                    className='inline-block w-16 h-16'
                    src={react}
                    alt="logo of react"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="text-lg font-semibold text-white">React</span>
                    <span className="px-2 py-1 bg-gray-600 rounded-lg text-md text-white font-medium min-w-[46px] text-center">7 YRS</span>
                  </div>
                  <SkillBar from={0} to={80} />
                </div>
              </div>
              <div className="flex flex-row">
                <div className="pr-4">
                  <Image
                    className='inline-block w-16 h-16'
                    src={typescript}
                    alt="logo of typescript"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="text-lg font-semibold text-white">TypeScript</span>
                    <span className="px-2 py-1 bg-gray-600 rounded-lg text-md text-white font-medium min-w-[46px] text-center">5 YRS</span>
                  </div>
                  <SkillBar from={0} to={70} />
                </div>
              </div>
              <div className="flex flex-row">
                <div className="pr-4">
                  <Image
                    className='inline-block w-16 h-16'
                    src={node}
                    alt="logo of nodejs"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <span className="text-lg font-semibold text-white">NodeJS</span>
                    <span className="px-2 py-1 bg-gray-600 rounded-lg text-md text-white font-medium min-w-[46px] text-center">4 YRS</span>
                  </div>
                  <SkillBar from={0} to={65} />
                </div>
              </div>
              <h3 className="mt-4 text-2xl font-semibold text-white">And more...</h3>
              <MoreSkills />
            </div>
          </div>
          <div className='mt-24'>
            <h1 className="text-3xl font-semibold text-white">
              Top Experience
            </h1>
            <div className="flex justify-around mt-8">
              <a href="https://www.coachhub.com/" title='CoachHub website' target="_blank">
                <div className="relative flex flex-col pt-8 pl-4 text-white border-4 rounded-lg cursor-pointer w-72 h-72" style={{
                  borderColor: "#f1583e"
                }}>
                  <h4 className="text-2xl font-semibold underline">CoachHub</h4>
                  <p>Senior Full Stack Developer</p>
                  <div
                    className="absolute px-4 py-2 text-xl font-semibold text-white bg-gray-700 rounded-lg -left-8 bottom-8"
                  >1 YR</div>
                  <Image src={link} className="absolute bg-white right-4 bottom-4" alt="link image" />
                </div></a>
              <a href="https://www2.deloitte.com/ph/en.html" title="Deloitte website" target="_blank">
                <div className="relative flex flex-col pt-8 pl-4 text-white border-4 rounded-lg cursor-pointer w-72 h-72" style={{
                  borderColor: "#86bc25"
                }}>
                  <h4 className="text-2xl font-semibold underline">Deloitte</h4>
                  <p>Senior Frontend Developer</p>
                  <div
                    className="absolute px-4 py-2 text-xl font-semibold text-white bg-gray-700 rounded-lg -left-8 bottom-8"
                  >4 YRS</div>
                  <Image src={link} className="absolute bg-white right-4 bottom-4" alt="link image" />
                </div></a>
              <a href="https://www.deltek.com/en" target="_blank" title="Deltek website">
                <div className="relative flex flex-col pt-8 pl-4 text-white border-4 rounded-lg cursor-pointer w-72 h-72" style={{
                  borderColor: "#00264a"
                }}>
                  <h4 className="text-2xl font-semibold underline">Deltek</h4>
                  <p>Senior Frontend Developer</p>
                  <div
                    className="absolute px-4 py-2 text-xl font-semibold text-white bg-gray-700 rounded-lg -left-8 bottom-8"
                  >5 YRS</div>
                  <Image src={link} className="absolute bg-white right-4 bottom-4" alt="link image" />
                </div></a>
            </div>
          </div>
          <div className='mt-24'>
            <h1 className="text-3xl font-semibold text-white">
              Demo Application
            </h1>
            <p>Simple demos to showcase on how I organize code.</p>
            <div className="relative flex items-center mt-8">
              <div className="flex flex-col w-full px-8 py-4 text-white bg-gray-900 border-2 border-gray-600 rounded-lg mt">
                <h4 className="mb-2 text-2xl font-semibold underline"><a href="https://github.com/sbalbalosa/custom-form" title="Custom form library on github" target="_blank">Custom Form</a></h4>
                <p>React form library that allows seamless combination of controlled and uncontrolled inputs in the same form. It provides a way to construct a form without separate configuration.</p>
              </div>
            </div>
            <div className="relative flex items-center mt-8">
              <div className="flex flex-col w-full px-8 py-4 text-white bg-gray-900 border-2 border-gray-600 rounded-lg mt">
                <h4 className="mb-2 text-2xl font-semibold underline">
                  <a href="https://github.com/sbalbalosa/starwars-characters" title="Starwars characters demo application on github" target="_blank">Starwars Characters</a>
                </h4>
                <p>This is a demo application that shows Star Wars characters which includes functionality such as saving, download csv and filtering records.</p>
              </div>
            </div>
          </div>
        </main>
      </div >
      <Footer />
    </>
  )
}
